### ISSUE TITLE
Default `sentry_error_handler` errors in R 4

### ISSUE THREAD

**Issue by afischer** [ozean12/sentryR#22]
Attempting to use sentryR with a plumber project in R 4 throws the following error when using the `sentry_error_handler`: `missing value where TRUE/FALSE needed`. 

This appears to be because within the handler, `req$HTTP_CONTENT_TYPE == "application/json"` returns a `logical(0)` and not a boolean.

**Comment by emilmahler** [comment]
I just encountered the same error. It seems this package is dead without a fix :(

**Comment by jwebbsoma** [comment]
I am experiencing the same issue

**Comment by jwebbsoma** [comment]
Upon further testing, it appears this issue only occurs with GET requests (empty bodies). I was able to get POSTs working and even GET requests that include a body (tested in Postman). Unfortunately, modern browsers don't allow sending a GET request with a body so this is effectively non functional. Definitely quite the issue still but maybe not completely killing the package.

**Comment by jwebbsoma** [comment]
I made a PR to fix this issue: https://github.com/ozean12/sentryR/pull/23 just need a moderator to merge it and release a new version to the CRAN.

**Comment by jcpsantiago** [comment]
Sorry for the delay everyone! I stopped getting notifications from this repo. I guess better late than ever, right? 😓 
Thank you @jwebbsoma ! PR merged. I will release the new version to CRAN too.
